version: "2.2"
services:
  dms:
    build: ./dms
    tty: true
    stdin_open: true
    depends_on:
      - db
    expose:
      - "8080"
    restart: always
    environment:
      - SECRETCOOKIE=cookie
      - WEBHOSTNAME=fileago.local.host 
  db:
    image: graphfoundation/ongdb:3.5.1
    expose:
      - "7474"
      - "7687"
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/mypass
  cad:
    build: ./cad
    expose:
      - "80"
    restart: always
    depends_on:
      - dms
  nginx:
    build: ./nginx
    ports:
      - "443:443"
    expose:
      - "9999"
    depends_on:
      - dms
      - cad
    restart: always
    environment:
      - WEBHOSTNAME=fileago.local.host 
  lool:
    build: ./lool
    expose:
      - "9980"
    depends_on:
      - dms
    restart: always
    cap_add:
      - MKNOD
